# the server your bot should connect to
server = "ws://games.zeus.gent:8080"
# URL for the lobby server
frontend = "https://games.zeus.gent"
# The command to use to start your bot
bot_argv = ["./bot-1"]
bot_token = "875e2e2fd9e7d1ce1b8df1ada51cfdddb30f9dc05a80457d59257c458ed99a72"
